name: Gradle CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # You were using Windows in Jenkins (CMD), so keeping it Windows

    env:
      GIT_REPO: https://github.com/rajadevops2025/gradledemo.git
      GIT_BRANCH: main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x gradlew
        shell: bash

      - name: Build Project
        run: ./gradlew clean build
        shell: bash

      - name: Run Tests
        run: ./gradlew test
        shell: bash

      - name: Package JAR
        run: ./gradlew jar
        shell: bash

      - name: Run Application
        run: java -jar build/libs/gradledemo-1.0.0.jar
        shell: bash

      - name: Archive JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-built-jar
          path: build/libs/*.jar

